# Generated by Django 5.1 on 2024-08-23 03:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
    ]
